GitHub Actions tests #6

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -45,7 +45,13 @@ jobs:
         run: mvn dependency:purge-local-repository
 
       - name: Retry failed Maven dependencies
-        run: mvn clean verify -Dmaven.test.failure.ignore=true -U
+        run: |
+          set +e  # Disable exit on first failure
+          for i in {1..3}; do
+            mvn clean verify -Dmaven.test.failure.ignore=true -U && break
+            echo "Maven build failed, retrying ($i/3)" || true
+          done
+          set -e  # Re-enable exit on failure
 
       - name: Debug JUnit XML files
         run: ls -la reports/surefire-reports/
